// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXs7x8t4W_gPPBwv_ciZzgLRgdsbSLedw',
    appId: '1:735672419145:web:578fc8cefaa31b65151098',
    messagingSenderId: '735672419145',
    projectId: 'desafiotecnico-app',
    authDomain: 'desafiotecnico-app.firebaseapp.com',
    storageBucket: 'desafiotecnico-app.firebasestorage.app',
    measurementId: 'G-0PPSCNK07Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3xzJo-8JT_JcKVfAEJtpY8-9Zp9i6jRk',
    appId: '1:735672419145:android:0dbfb43b51a97ebb151098',
    messagingSenderId: '735672419145',
    projectId: 'desafiotecnico-app',
    storageBucket: 'desafiotecnico-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6ZEVinwjUjW5KzdW0i-W4u6Ayf0vPbU',
    appId: '1:735672419145:ios:9e6b4582b31f588d151098',
    messagingSenderId: '735672419145',
    projectId: 'desafiotecnico-app',
    storageBucket: 'desafiotecnico-app.firebasestorage.app',
    iosBundleId: 'com.example.desafioTecnico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6ZEVinwjUjW5KzdW0i-W4u6Ayf0vPbU',
    appId: '1:735672419145:ios:9e6b4582b31f588d151098',
    messagingSenderId: '735672419145',
    projectId: 'desafiotecnico-app',
    storageBucket: 'desafiotecnico-app.firebasestorage.app',
    iosBundleId: 'com.example.desafioTecnico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXs7x8t4W_gPPBwv_ciZzgLRgdsbSLedw',
    appId: '1:735672419145:web:04d9cea880f22076151098',
    messagingSenderId: '735672419145',
    projectId: 'desafiotecnico-app',
    authDomain: 'desafiotecnico-app.firebaseapp.com',
    storageBucket: 'desafiotecnico-app.firebasestorage.app',
    measurementId: 'G-HQVNH8JE6B',
  );
}